-- Branch foundation: Branch table, branchId scoping columns, Role enum
-- expansion (ADMIN -> SUPER_ADMIN), EmployeeStatus, and the shared
-- Attachment table. Hand-written (not autogenerated) because several
-- tables already have production rows, so columns must be added nullable,
-- backfilled, then tightened to NOT NULL.

-- 1. New enums and the Branch table itself (referenced by everything below).
CREATE TYPE "EmployeeStatus" AS ENUM ('ACTIVE', 'IDLE', 'ON_VACATION', 'TERMINATED');

CREATE TABLE "Branch" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "emirate" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Branch_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Branch_code_key" ON "Branch"("code");

-- Seed the one branch every existing row will be backfilled into.
INSERT INTO "Branch" ("id", "code", "name")
VALUES ('branch_main', 'MAIN', COALESCE((SELECT "issuedTo" FROM "Settings" WHERE "id" = 'singleton'), 'Main Branch'));

-- 2. Attachment table (net-new, no backfill needed).
CREATE TABLE "Attachment" (
    "id" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "docType" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "fileData" BYTEA NOT NULL,
    "mimeType" TEXT NOT NULL,
    "expiryDate" TIMESTAMP(3),
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "branchId" TEXT,
    "uploadedById" TEXT NOT NULL,

    CONSTRAINT "Attachment_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "Attachment_entityType_entityId_idx" ON "Attachment"("entityType", "entityId");
CREATE INDEX "Attachment_branchId_docType_idx" ON "Attachment"("branchId", "docType");

ALTER TABLE "Attachment" ADD CONSTRAINT "Attachment_uploadedById_fkey"
  FOREIGN KEY ("uploadedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- 3. Add branchId nullable everywhere first (safe on populated tables).
ALTER TABLE "User" ADD COLUMN "branchId" TEXT;
ALTER TABLE "Upload" ADD COLUMN "branchId" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "branchId" TEXT;
ALTER TABLE "Client" ADD COLUMN "branchId" TEXT;
ALTER TABLE "ClientInvoice" ADD COLUMN "branchId" TEXT;
ALTER TABLE "TimesheetEntry" ADD COLUMN "branchId" TEXT;
ALTER TABLE "GeneratedSheet" ADD COLUMN "branchId" TEXT;
ALTER TABLE "Project" ADD COLUMN "branchId" TEXT;
ALTER TABLE "InventoryItem" ADD COLUMN "branchId" TEXT;

-- Employee: branchId nullable-first, status gets its real default immediately
-- since it's a static default and safe on populated tables in one step.
ALTER TABLE "Employee" ADD COLUMN "branchId" TEXT;
ALTER TABLE "Employee" ADD COLUMN "status" "EmployeeStatus" NOT NULL DEFAULT 'ACTIVE';

-- 4. Backfill every existing row into the MAIN branch.
UPDATE "User" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL AND "role" <> 'ADMIN';
UPDATE "Upload" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;
UPDATE "Supplier" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;
UPDATE "Client" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;
UPDATE "ClientInvoice" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;
UPDATE "TimesheetEntry" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;
UPDATE "GeneratedSheet" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;
UPDATE "Project" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;
UPDATE "InventoryItem" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;
UPDATE "Employee" SET "branchId" = 'branch_main' WHERE "branchId" IS NULL;

-- Note: existing ADMIN users are left with branchId = NULL on purpose —
-- they become SUPER_ADMIN below, which is cross-branch by design.

-- 5. Correct the Employee status backfill (overrides the blanket ACTIVE default
--    from step 3 for rows that are actually terminated or benched).
UPDATE "Employee" SET "status" = 'TERMINATED' WHERE "active" = false;
UPDATE "Employee" SET "status" = 'IDLE' WHERE "active" = true AND "projectId" IS NULL;

-- 6. Tighten to NOT NULL now that every row has a value (User stays nullable
--    — SUPER_ADMIN is cross-branch by design).
ALTER TABLE "Upload" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "Supplier" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "Client" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "ClientInvoice" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "TimesheetEntry" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "GeneratedSheet" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "Project" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "InventoryItem" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "Employee" ALTER COLUMN "branchId" SET NOT NULL;

CREATE INDEX "TimesheetEntry_branchId_idx" ON "TimesheetEntry"("branchId");

-- 7. Foreign keys, now that every referencing column is populated correctly.
ALTER TABLE "User" ADD CONSTRAINT "User_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Upload" ADD CONSTRAINT "Upload_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Supplier" ADD CONSTRAINT "Supplier_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Client" ADD CONSTRAINT "Client_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ClientInvoice" ADD CONSTRAINT "ClientInvoice_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TimesheetEntry" ADD CONSTRAINT "TimesheetEntry_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GeneratedSheet" ADD CONSTRAINT "GeneratedSheet_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InventoryItem" ADD CONSTRAINT "InventoryItem_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- 8. Role enum: SUPER_ADMIN/BRANCH_ADMIN/STAFF replaces ADMIN/STAFF.
-- Existing ADMIN rows are mapped to SUPER_ADMIN in the same USING cast that
-- creates the new type, so there is no window where a row holds a value the
-- new type doesn't recognize yet.
BEGIN;
CREATE TYPE "Role_new" AS ENUM ('SUPER_ADMIN', 'BRANCH_ADMIN', 'STAFF');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING (
  CASE "role"::text
    WHEN 'ADMIN' THEN 'SUPER_ADMIN'
    ELSE "role"::text
  END
)::"Role_new";
ALTER TYPE "Role" RENAME TO "Role_old";
ALTER TYPE "Role_new" RENAME TO "Role";
DROP TYPE "Role_old";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'STAFF';
COMMIT;
