import Link from "next/link";
import { prisma } from "@/lib/db";
import { monthLabelFromKey } from "@/lib/timesheetSummary";

export default async function HistoryPage() {
  const sheets = await prisma.generatedSheet.findMany({
    orderBy: { generatedAt: "desc" },
    take: 100,
    include: { supplier: true, generatedBy: true },
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-slate-900">History</h1>
        <p className="mt-1 text-sm text-slate-500">
          Every timesheet generated, most recent first. Reopen a company&rsquo;s
          review screen to regenerate with the latest figures.
        </p>
      </div>

      {sheets.length === 0 ? (
        <div className="rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center">
          <p className="text-sm text-slate-500">
            Nothing generated yet.{" "}
            <Link href="/companies" className="font-medium text-slate-900 underline">
              Go to Companies
            </Link>{" "}
            to generate a sheet.
          </p>
        </div>
      ) : (
        <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white">
          <table className="w-full text-sm">
            <thead className="border-b border-slate-200 bg-slate-50 text-left text-xs font-medium uppercase tracking-wide text-slate-500">
              <tr>
                <th className="px-4 py-3">Company</th>
                <th className="px-4 py-3">Month</th>
                <th className="px-4 py-3">Format</th>
                <th className="px-4 py-3 text-right">Gas deduction</th>
                <th className="px-4 py-3">Issued to</th>
                <th className="px-4 py-3">Generated by</th>
                <th className="px-4 py-3">When</th>
                <th className="px-4 py-3" />
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {sheets.map((s) => (
                <tr key={s.id}>
                  <td className="px-4 py-3 font-medium text-slate-900">
                    {s.supplier.name}
                  </td>
                  <td className="px-4 py-3 text-slate-600">
                    {monthLabelFromKey(s.month)}
                  </td>
                  <td className="px-4 py-3 text-slate-600 uppercase">
                    {s.format}
                  </td>
                  <td className="px-4 py-3 text-right text-slate-600">
                    {s.gasDeduction.toLocaleString(undefined, {
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2,
                    })}
                  </td>
                  <td className="px-4 py-3 text-slate-600">{s.issuedTo}</td>
                  <td className="px-4 py-3 text-slate-600">
                    {s.generatedBy.name}
                  </td>
                  <td className="px-4 py-3 text-slate-500">
                    {new Date(s.generatedAt).toLocaleString("en-GB", {
                      day: "2-digit",
                      month: "short",
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <Link
                      href={`/companies/${s.supplier.id}/generate?month=${s.month}`}
                      className="text-xs font-medium text-blue-600 hover:underline"
                    >
                      Reopen →
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
