import Link from "next/link";
import { prisma } from "@/lib/db";
import { monthLabelFromKey } from "@/lib/timesheetSummary";
import { requireUserWithBranch } from "@/lib/auth";
import { branchWhere } from "@/lib/branch";

export default async function HistoryPage() {
  const { branchId } = await requireUserWithBranch();
  const sheets = await prisma.generatedSheet.findMany({
    where: branchWhere(branchId),
    orderBy: { generatedAt: "desc" },
    take: 100,
    include: { supplier: true, generatedBy: true },
  });

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-xl tracking-tight text-primary font-semibold">History</h1>
        <p className="mt-1 text-sm text-muted">
          Every timesheet generated, most recent first. Reopen a company&rsquo;s
          review screen to regenerate with the latest figures.
        </p>
      </div>

      {sheets.length === 0 ? (
        <div className="empty-state">
          <p className="text-sm text-muted">
            Nothing generated yet.{" "}
            <Link href="/companies" className="font-medium text-primary underline">
              Go to Companies
            </Link>{" "}
            to generate a sheet.
          </p>
        </div>
      ) : (
        <div className="card overflow-hidden">
          <table className="w-full text-sm">
            <thead className="border-b border-default bg-surface-subtle text-left text-xs font-medium uppercase tracking-wide text-muted">
              <tr>
                <th className="px-4 py-3">Company</th>
                <th className="px-4 py-3">Month</th>
                <th className="px-4 py-3">Format</th>
                <th className="px-4 py-3 text-right">Gas deduction</th>
                <th className="px-4 py-3">Issued to</th>
                <th className="px-4 py-3">Generated by</th>
                <th className="px-4 py-3">When</th>
                <th className="px-4 py-3" />
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--border)]">
              {sheets.map((s) => (
                <tr key={s.id}>
                  <td className="px-4 py-3 font-medium text-primary">
                    {s.supplier.name}
                  </td>
                  <td className="px-4 py-3 text-secondary">
                    {monthLabelFromKey(s.month)}
                  </td>
                  <td className="px-4 py-3 text-secondary uppercase">
                    {s.format}
                  </td>
                  <td className="px-4 py-3 text-right text-secondary">
                    {s.gasDeduction.toLocaleString(undefined, {
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2,
                    })}
                  </td>
                  <td className="px-4 py-3 text-secondary">{s.issuedTo}</td>
                  <td className="px-4 py-3 text-secondary">
                    {s.generatedBy.name}
                  </td>
                  <td className="px-4 py-3 text-muted">
                    {new Date(s.generatedAt).toLocaleString("en-GB", {
                      day: "2-digit",
                      month: "short",
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <Link
                      href={`/companies/${s.supplier.id}/generate?month=${s.month}`}
                      className="text-xs font-medium text-blue-600 hover:underline"
                    >
                      Reopen →
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
